subgraphs: 
  accounts: 
    routing_url : "http://localhost:4051/"
    schema: 
      file: ./subgraphs/accounts.graphql
  inventory: 
    routing_url: "http://localhost:5052/graphql"
    schema: 
      file: ./subgraphs/inventory.graphql
  products: 
    routing_url: "http://localhost:5053/graphql"
    schema: 
      file: ./subgraphs/products.graphql
  reviews: 
    routing_url: "http://localhost:5054/graphql"
    schema: 
      file: ./subgraphs/reviews.graphql
